apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-back
  labels:
    app: card-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card-back
  template:
    metadata:
      labels:
        app: card-back
    spec:
      containers:
        - name: card-back
          image: josefirstacr.azurecr.io/test
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
   name: card-balancer
spec:
  selector:
    app: card-balancer
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer